version: 0.2
    
phases:
  install:
    runtime-versions:
      dotnet: 6.0

  pre_build:
    commands:
      - echo Restore started on `date`
      - dotnet restore Api.Backend/Api.Backend.csproj
      
  build:
    commands:
      - echo Build started on `date`
      - dotnet build Api.Backend/*.csproj
      - echo Test started on `date`
      - dotnet test Api.Backend/*.csproj
      
  post_build:
    commands:
      - echo Publish started on `date`
      - dotnet publish -c Release -r linux-x64 -o ./ Api.Backend/*.csproj
      
artifacts:
  files:
    - ./**/*