version: '3.4'

services:
  api.backend:
    image: ${DOCKER_REGISTRY-}apibackend
    container_name: donateback
    build:
      context: .
      dockerfile: Api.Backend/Dockerfile
    depends_on: 
      - database
    ports:
      - "5000:80"
    networks:
      - donate-network
    restart: always
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DonateConnection=server=donatemysqldb;database=donatedb;user=root;password=wagner123456"
    command: ["dotnet", "ef", "database update"]

  database:
    image: mysql:8.0.22
    container_name: donatemysqldb
    ports:
      - "3308:3306"
    expose: 
      - 3308
    volumes:
      - db-volume:/var/lib/mysql
    restart: always
    networks:
      - donate-network
    environment: 
      MYSQL_ROOT_PASSWORD: wagner123456
      MYSQL_USER: root
      MYSQL_PASSWORD: wagner123456
      MYSQL_DATABASE: donatedb
volumes:
  db-volume:

networks:
  donate-network:
    driver: bridge